### ISSUE TITLE
mcn user service crashing 

### ISSUE THREAD

**Issue by UriZ** [UriZ/mcn-project-management#35]
Connected to db
2018-05-21T15:48:58.566516+00:00 app[web.1]: /app/node_modules/mongodb/lib/utils.js:132
2018-05-21T15:48:58.566520+00:00 app[web.1]:       throw err;
2018-05-21T15:48:58.566522+00:00 app[web.1]:       ^
2018-05-21T15:48:58.566523+00:00 app[web.1]: 
2018-05-21T15:48:58.566526+00:00 app[web.1]: TypeError: Cannot read property 'preferences' of null
2018-05-21T15:48:58.566527+00:00 app[web.1]:     at collection.findOne (/app/controllers/users.js:255:42)
2018-05-21T15:48:58.566530+00:00 app[web.1]:     at args.push (/app/node_modules/mongodb/lib/utils.js:404:72)
2018-05-21T15:48:58.566531+00:00 app[web.1]:     at handleCallback (/app/node_modules/mongodb/lib/utils.js:128:55)
2018-05-21T15:48:58.566533+00:00 app[web.1]:     at /app/node_modules/mongodb/lib/collection.js:1357:5
2018-05-21T15:48:58.566535+00:00 app[web.1]:     at args.push (/app/node_modules/mongodb/lib/utils.js:404:72)
2018-05-21T15:48:58.566536+00:00 app[web.1]:     at handleCallback (/app/node_modules/mongodb/lib/utils.js:128:55)
2018-05-21T15:48:58.566538+00:00 app[web.1]:     at /app/node_modules/mongodb/lib/cursor.js:751:5
2018-05-21T15:48:58.566539+00:00 app[web.1]:     at handleCallback (/app/node_modules/mongodb-core/lib/cursor.js:178:5)
2018-05-21T15:48:58.566541+00:00 app[web.1]:     at setCursorNotified (/app/node_modules/mongodb-core/lib/cursor.js:555:3)
2018-05-21T15:48:58.566542+00:00 app[web.1]:     at /app/node_modules/mongodb-core/lib/cursor.js:664:16
2018-05-21T15:48:58.586234+00:00 heroku[router]: at=error code=H13 desc="Connection closed without response" method=GET path="/api/users/10159941643255344/preferences" host=mcn-user-service.herokuapp.com request_id=895e44be-7890-4a26-93df-426224a267aa fwd="54.158.151.31" dyno=web.1 connect=5000ms service=399ms status=503 bytes=0 protocol=https
2018-05-21T15:48:58.650412+00:00 heroku[web.1]: Process exited with status 1
2018-05-21T15:48:58.784590+00:00 heroku[web.1]: State changed from up to crashed
2018-05-21T15:49:16.140344+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/api/users/105712723589549/preferences" host=mcn-user-service.herokuapp.com request_id=9f6742e5-8c91-4aa6-b479-50d2ddc89418 fwd="54.158.243.227" dyno= connect= service= status=503 bytes= protocol=https
2018-05-21T15:49:18.432495+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/api/users/105712723589549/preferences" host=mcn-user-service.herokuapp.com request_id=bcaa4348-9395-417e-823a-d1f6cceacbab fwd="54.158.151.31" dyno= connect= service= status=503 bytes= protocol=https
2018-05-21T15:49:27.672308+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/api/users/105712723589549/preferences" host=mcn-user-service.herokuapp.com request_id=cbf22da3-66ba-459c-985a-2236bfb77f28 fwd="54.158.243.227" dyno= connect= service= status=503 bytes= protocol=https
2018-05-21T15:49:27.975887+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/api/users/105712723589549/preferences" host=mcn-user-service.herokuapp.com request_id=ecd4d656-7d93-4422-b2d2-fff7ade5153c fwd="54.158.151.31" dyno= connect= service= status=503 bytes= protocol=https
2018-05-21T15:50:01.429115+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=mcn-user-service.herokuapp.com request_id=20735317-058f-4e50-b83d-63997757a1e6 fwd="79.176.87.202" dyno= connect= service= status=503 bytes= protocol=https

**Comment by UriZ** [comment]
priblem is on the client we just do a fb login, but dont check to see that there is a user
