### ISSUE TITLE
clicking the filter fails due to schema validatoin error on preferences update 

### ISSUE THREAD

**Issue by UriZ** [UriZ/mcn-project-management#36]
Error: Parameter (preferences) failed schema validation
2018-05-21T16:01:16.465599+00:00 app[web.1]:     at throwErrorWithCode (/app/node_modules/swagger-tools/lib/validators.js:116:13)
2018-05-21T16:01:16.465610+00:00 app[web.1]:     at Object.module.exports.validateAgainstSchema (/app/node_modules/swagger-tools/lib/validators.js:171:7)
2018-05-21T16:01:16.465612+00:00 app[web.1]:     at /app/node_modules/swagger-tools/middleware/swagger-validator.js:143:22
2018-05-21T16:01:16.465615+00:00 app[web.1]:     at /app/node_modules/async/dist/async.js:1121:9
2018-05-21T16:01:16.465616+00:00 app[web.1]:     at eachOfArrayLike (/app/node_modules/async/dist/async.js:1055:9)
2018-05-21T16:01:16.465618+00:00 app[web.1]:     at eachOf (/app/node_modules/async/dist/async.js:1103:5)
2018-05-21T16:01:16.465624+00:00 app[web.1]:     at _asyncMap (/app/node_modules/async/dist/async.js:1119:5)
2018-05-21T16:01:16.465626+00:00 app[web.1]:     at Object.map (/app/node_modules/async/dist/async.js:1108:16)
2018-05-21T16:01:16.465628+00:00 app[web.1]:     at validateValue (/app/node_modules/swagger-tools/middleware/swagger-validator.js:136:11)
2018-05-21T16:01:16.465630+00:00 app[web.1]:     at /app/node_modules/swagger-tools/middleware/swagger-validator.js:379:21
2018-05-21T16:01:16.465631+00:00 app[web.1]:     at /app/node_modules/async/dist/async.js:1121:9
2018-05-21T16:01:16.465633+00:00 app[web.1]:     at eachOfArrayLike (/app/node_modules/async/dist/async.js:1055:9)
2018-05-21T16:01:16.465635+00:00 app[web.1]:     at eachOf (/app/node_modules/async/dist/async.js:1103:5)
2018-05-21T16:01:16.465637+00:00 app[web.1]:     at _asyncMap (/app/node_modules/async/dist/async.js:1119:5)
2018-05-21T16:01:16.465639+00:00 app[web.1]:     at Object.map (/app/node_modules/async/dist/async.js:1108:16)
2018-05-21T16:01:16.465640+00:00 app[web.1]:     at swaggerValidator (/app/node_modules/swagger-tools/middleware/swagger-validator.js:358:15)
2018-05-21T16:01:16.465642+00:00 app[web.1]:     at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
2018-05-21T16:01:16.465644+00:00 app[web.1]:     at trim_prefix (/app/node_modules/express/lib/router/index.js:317:13)
2018-05-21T16:01:16.465646+00:00 app[web.1]:     at /app/node_modules/express/lib/router/index.js:284:7
2018-05-21T16:01:16.465648+00:00 app[web.1]:     at Function.process_params (/app/node_modules/express/lib/router/index.js:335:12)
2018-05-21T16:01:16.465650+00:00 app[web.1]:     at next (/app/node_modules/express/lib/router/index.js:275:10)
2018-05-21T16:01:16.465651+00:00 app[web.1]:     at /app/authentication/facebookAuth.js:52:17
Uris-MacBook-Pro:~ uriz$

**Comment by UriZ** [comment]
the problem was with int values in the db - old value. need to change pre creating code in user serice
